name: pointcept
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - pyg
dependencies:
  - python=3.10
  - ninja
  - pytorch=2.7.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.8
  - h5py
  - pyyaml
  - sharedarray
  - tensorboard
  - tensorboardx
  - yapf
  - addict
  - einops
  - scipy
  - plyfile
  - termcolor
  - timm
  - pytorch-cluster
  - pytorch-scatter
  - pytorch-sparse
  - pip
  - pip:
      - torch-geometric
      - spconv-cu120
      - ftfy
      - regex
      - tqdm
      - git+https://github.com/openai/CLIP.git
      - packaging
      - flash-attn --no-build-isolation --no-cache-dir
